use crate::entities::Entity;
use crate::storyboard::{Act, Action, Event, Maneuver, ManeuverGroup, Story};
use crate::Position;
use crate::{Result, Scenario, ScenarioError};
use quick_xml::events::{BytesEnd, BytesStart, Event as XmlEvent};
use quick_xml::Writer;
use std::io::Cursor;

impl Scenario {
    pub fn to_xml(&self) -> Result<String> {
        let mut writer = Writer::new_with_indent(Cursor::new(Vec::new()), b' ', 2);

        // XML declaration
        writer
            .write_event(XmlEvent::Decl(quick_xml::events::BytesDecl::new(
                "1.0",
                Some("UTF-8"),
                None,
            )))
            .map_err(|e| {
                ScenarioError::Xml(quick_xml::Error::Io(std::sync::Arc::new(
                    std::io::Error::other(e.to_string()),
                )))
            })?;

        // Root element
        let mut root = BytesStart::new("OpenSCENARIO");
        root.push_attribute(("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance"));
        root.push_attribute(("xsi:noNamespaceSchemaLocation", "OpenSCENARIO.xsd"));
        writer.write_event(XmlEvent::Start(root.borrow()))?;

        // FileHeader
        self.write_file_header(&mut writer)?;

        // ParameterDeclarations (if any)
        if !self.parameters.is_empty() {
            self.write_parameter_declarations(&mut writer)?;
        }

        // CatalogLocations (empty for now)
        writer.write_event(XmlEvent::Empty(BytesStart::new("CatalogLocations")))?;

        // RoadNetwork (empty for now)
        writer.write_event(XmlEvent::Empty(BytesStart::new("RoadNetwork")))?;

        // Entities
        self.write_entities(&mut writer)?;

        // Storyboard
        self.write_storyboard(&mut writer)?;

        writer.write_event(XmlEvent::End(BytesEnd::new("OpenSCENARIO")))?;

        let result = writer.into_inner().into_inner();
        String::from_utf8(result).map_err(|e| {
            ScenarioError::Xml(quick_xml::Error::Io(std::sync::Arc::new(
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("Invalid UTF-8 in generated XML: {}", e),
                ),
            )))
        })
    }

    fn write_file_header<W: std::io::Write>(&self, writer: &mut Writer<W>) -> Result<()> {
        let mut elem = BytesStart::new("FileHeader");
        elem.push_attribute(("revMajor", self.version().major().to_string().as_str()));
        elem.push_attribute(("revMinor", self.version().minor().to_string().as_str()));
        elem.push_attribute(("date", "2026-04-30T00:00:00"));
        elem.push_attribute(("description", "Generated by openscenario-mcp"));
        elem.push_attribute(("author", "openscenario-mcp"));
        writer.write_event(XmlEvent::Empty(elem))?;
        Ok(())
    }

    fn write_parameter_declarations<W: std::io::Write>(&self, writer: &mut Writer<W>) -> Result<()> {
        writer.write_event(XmlEvent::Start(BytesStart::new("ParameterDeclarations")))?;

        for param in &self.parameters {
            let mut elem = BytesStart::new("ParameterDeclaration");
            elem.push_attribute(("name", param.name.as_str()));
            
            let param_type_str = match param.parameter_type {
                crate::scenario::ParameterType::Integer => "integer",
                crate::scenario::ParameterType::Double => "double",
                crate::scenario::ParameterType::String => "string",
                crate::scenario::ParameterType::Boolean => "boolean",
            };
            elem.push_attribute(("parameterType", param_type_str));
            elem.push_attribute(("value", param.value.as_str()));
            
            writer.write_event(XmlEvent::Empty(elem))?;
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("ParameterDeclarations")))?;
        Ok(())
    }

    fn write_entities<W: std::io::Write>(&self, writer: &mut Writer<W>) -> Result<()> {
        writer.write_event(XmlEvent::Start(BytesStart::new("Entities")))?;

        for entity in self.entities() {
            self.write_entity(writer, entity)?;
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("Entities")))?;
        Ok(())
    }

    fn write_entity<W: std::io::Write>(
        &self,
        writer: &mut Writer<W>,
        entity: &Entity,
    ) -> Result<()> {
        let mut elem = BytesStart::new("ScenarioObject");
        elem.push_attribute(("name", entity.name()));
        writer.write_event(XmlEvent::Start(elem))?;

        match entity {
            Entity::Vehicle(v) => {
                // If catalog is provided, use CatalogReference
                if let Some(catalog) = &v.params.catalog {
                    let mut ref_elem = BytesStart::new("CatalogReference");
                    ref_elem.push_attribute(("catalogName", catalog.path.as_str()));
                    ref_elem.push_attribute(("entryName", catalog.entry_name.as_str()));
                    writer.write_event(XmlEvent::Empty(ref_elem))?;
                } else {
                    // Inline vehicle definition
                    let mut veh_elem = BytesStart::new("Vehicle");
                    veh_elem.push_attribute(("name", v.name.as_str()));
                    veh_elem.push_attribute((
                        "vehicleCategory",
                        format!("{:?}", v.params.vehicle_category)
                            .to_lowercase()
                            .as_str(),
                    ));
                    if let Some(props) = &v.params.properties {
                        if let Some(model) = &props.model3d {
                            veh_elem.push_attribute(("model3d", model.as_str()));
                        }
                    }
                    writer.write_event(XmlEvent::Start(veh_elem))?;

                    // BoundingBox (using defaults)
                    writer.write_event(XmlEvent::Start(BytesStart::new("BoundingBox")))?;
                    let mut center = BytesStart::new("Center");
                    center.push_attribute(("x", "1.4"));
                    center.push_attribute(("y", "0.0"));
                    center.push_attribute(("z", "0.9"));
                    writer.write_event(XmlEvent::Empty(center))?;
                    let mut dims = BytesStart::new("Dimensions");
                    dims.push_attribute(("width", "2.0"));
                    dims.push_attribute(("length", "5.0"));
                    dims.push_attribute(("height", "1.8"));
                    writer.write_event(XmlEvent::Empty(dims))?;
                    writer.write_event(XmlEvent::End(BytesEnd::new("BoundingBox")))?;

                    // Performance (using defaults)
                    let mut perf = BytesStart::new("Performance");
                    perf.push_attribute(("maxSpeed", "69"));
                    perf.push_attribute(("maxDeceleration", "30"));
                    perf.push_attribute(("maxAcceleration", "10"));
                    writer.write_event(XmlEvent::Empty(perf))?;

                    // Axles (using defaults)
                    writer.write_event(XmlEvent::Start(BytesStart::new("Axles")))?;
                    let mut front = BytesStart::new("FrontAxle");
                    front.push_attribute(("maxSteering", "30"));
                    front.push_attribute(("wheelDiameter", "0.8"));
                    front.push_attribute(("trackWidth", "1.68"));
                    front.push_attribute(("positionX", "2.98"));
                    front.push_attribute(("positionZ", "0.4"));
                    writer.write_event(XmlEvent::Empty(front))?;
                    let mut rear = BytesStart::new("RearAxle");
                    rear.push_attribute(("maxSteering", "30"));
                    rear.push_attribute(("wheelDiameter", "0.8"));
                    rear.push_attribute(("trackWidth", "1.68"));
                    rear.push_attribute(("positionX", "0"));
                    rear.push_attribute(("positionZ", "0.4"));
                    writer.write_event(XmlEvent::Empty(rear))?;
                    writer.write_event(XmlEvent::End(BytesEnd::new("Axles")))?;

                    // Properties (if mass is specified)
                    if let Some(props) = &v.params.properties {
                        if props.mass.is_some() {
                            writer.write_event(XmlEvent::Start(BytesStart::new("Properties")))?;
                            if let Some(mass) = props.mass {
                                let mut prop = BytesStart::new("Property");
                                prop.push_attribute(("name", "mass"));
                                prop.push_attribute(("value", mass.to_string().as_str()));
                                writer.write_event(XmlEvent::Empty(prop))?;
                            }
                            writer.write_event(XmlEvent::End(BytesEnd::new("Properties")))?;
                        }
                    }

                    writer.write_event(XmlEvent::End(BytesEnd::new("Vehicle")))?;
                }
            }
            Entity::Pedestrian(p) => {
                // If catalog is provided, use CatalogReference
                if let Some(catalog) = &p.params.catalog {
                    let mut ref_elem = BytesStart::new("CatalogReference");
                    ref_elem.push_attribute(("catalogName", catalog.path.as_str()));
                    ref_elem.push_attribute(("entryName", catalog.entry_name.as_str()));
                    writer.write_event(XmlEvent::Empty(ref_elem))?;
                } else {
                    // Inline pedestrian definition
                    let mut ped_elem = BytesStart::new("Pedestrian");
                    ped_elem.push_attribute(("name", p.name.as_str()));
                    ped_elem.push_attribute(("pedestrianCategory", "pedestrian"));
                    if let Some(model) = &p.params.model {
                        ped_elem.push_attribute(("model3d", model.as_str()));
                    }
                    writer.write_event(XmlEvent::Start(ped_elem))?;

                    // BoundingBox (pedestrian defaults)
                    writer.write_event(XmlEvent::Start(BytesStart::new("BoundingBox")))?;
                    let mut center = BytesStart::new("Center");
                    center.push_attribute(("x", "0.0"));
                    center.push_attribute(("y", "0.0"));
                    center.push_attribute(("z", "0.9"));
                    writer.write_event(XmlEvent::Empty(center))?;
                    let mut dims = BytesStart::new("Dimensions");
                    dims.push_attribute(("width", "0.5"));
                    dims.push_attribute(("length", "0.5"));
                    dims.push_attribute(("height", "1.8"));
                    writer.write_event(XmlEvent::Empty(dims))?;
                    writer.write_event(XmlEvent::End(BytesEnd::new("BoundingBox")))?;

                    // Properties (if mass is specified)
                    if p.params.mass.is_some() {
                        writer.write_event(XmlEvent::Start(BytesStart::new("Properties")))?;
                        if let Some(mass) = p.params.mass {
                            let mut prop = BytesStart::new("Property");
                            prop.push_attribute(("name", "mass"));
                            prop.push_attribute(("value", mass.to_string().as_str()));
                            writer.write_event(XmlEvent::Empty(prop))?;
                        }
                        writer.write_event(XmlEvent::End(BytesEnd::new("Properties")))?;
                    }

                    writer.write_event(XmlEvent::End(BytesEnd::new("Pedestrian")))?;
                }
            }
            Entity::MiscObject(m) => {
                // If catalog is provided, use CatalogReference
                if let Some(catalog) = &m.params.catalog {
                    let mut ref_elem = BytesStart::new("CatalogReference");
                    ref_elem.push_attribute(("catalogName", catalog.path.as_str()));
                    ref_elem.push_attribute(("entryName", catalog.entry_name.as_str()));
                    writer.write_event(XmlEvent::Empty(ref_elem))?;
                } else {
                    // Inline misc object definition
                    let mut misc_elem = BytesStart::new("MiscObject");
                    misc_elem.push_attribute(("name", m.name.as_str()));
                    let category = m.params.category.as_deref().unwrap_or("obstacle");
                    misc_elem.push_attribute(("miscObjectCategory", category));
                    writer.write_event(XmlEvent::Start(misc_elem))?;

                    // BoundingBox (misc object defaults)
                    writer.write_event(XmlEvent::Start(BytesStart::new("BoundingBox")))?;
                    let mut center = BytesStart::new("Center");
                    center.push_attribute(("x", "0.0"));
                    center.push_attribute(("y", "0.0"));
                    center.push_attribute(("z", "0.5"));
                    writer.write_event(XmlEvent::Empty(center))?;
                    let mut dims = BytesStart::new("Dimensions");
                    dims.push_attribute(("width", "1.0"));
                    dims.push_attribute(("length", "1.0"));
                    dims.push_attribute(("height", "1.0"));
                    writer.write_event(XmlEvent::Empty(dims))?;
                    writer.write_event(XmlEvent::End(BytesEnd::new("BoundingBox")))?;

                    // Properties (if mass is specified)
                    if m.params.mass.is_some() {
                        writer.write_event(XmlEvent::Start(BytesStart::new("Properties")))?;
                        if let Some(mass) = m.params.mass {
                            let mut prop = BytesStart::new("Property");
                            prop.push_attribute(("name", "mass"));
                            prop.push_attribute(("value", mass.to_string().as_str()));
                            writer.write_event(XmlEvent::Empty(prop))?;
                        }
                        writer.write_event(XmlEvent::End(BytesEnd::new("Properties")))?;
                    }

                    writer.write_event(XmlEvent::End(BytesEnd::new("MiscObject")))?;
                }
            }
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("ScenarioObject")))?;
        Ok(())
    }

    fn write_storyboard<W: std::io::Write>(&self, writer: &mut Writer<W>) -> Result<()> {
        writer.write_event(XmlEvent::Start(BytesStart::new("Storyboard")))?;

        // Init
        self.write_init(writer)?;

        // Stories
        for story in self.storyboard.stories.values() {
            self.write_story(writer, story)?;
        }

        // StopTrigger
        self.write_stop_trigger(writer)?;

        writer.write_event(XmlEvent::End(BytesEnd::new("Storyboard")))?;
        Ok(())
    }

    fn write_init<W: std::io::Write>(&self, writer: &mut Writer<W>) -> Result<()> {
        writer.write_event(XmlEvent::Start(BytesStart::new("Init")))?;
        writer.write_event(XmlEvent::Start(BytesStart::new("Actions")))?;

        for (entity_name, position) in self.initial_positions() {
            let mut private_elem = BytesStart::new("Private");
            private_elem.push_attribute(("entityRef", entity_name.as_str()));
            writer.write_event(XmlEvent::Start(private_elem))?;

            writer.write_event(XmlEvent::Start(BytesStart::new("PrivateAction")))?;
            writer.write_event(XmlEvent::Start(BytesStart::new("TeleportAction")))?;
            self.write_position(writer, position)?;
            writer.write_event(XmlEvent::End(BytesEnd::new("TeleportAction")))?;
            writer.write_event(XmlEvent::End(BytesEnd::new("PrivateAction")))?;

            writer.write_event(XmlEvent::End(BytesEnd::new("Private")))?;
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("Actions")))?;
        writer.write_event(XmlEvent::End(BytesEnd::new("Init")))?;
        Ok(())
    }

    fn write_position<W: std::io::Write>(
        &self,
        writer: &mut Writer<W>,
        position: &Position,
    ) -> Result<()> {
        writer.write_event(XmlEvent::Start(BytesStart::new("Position")))?;

        match position {
            Position::World { x, y, z, h, p, r } => {
                let mut elem = BytesStart::new("WorldPosition");
                elem.push_attribute(("x", x.to_string().as_str()));
                elem.push_attribute(("y", y.to_string().as_str()));
                elem.push_attribute(("z", z.to_string().as_str()));
                elem.push_attribute(("h", h.to_string().as_str()));
                elem.push_attribute(("p", p.to_string().as_str()));
                elem.push_attribute(("r", r.to_string().as_str()));
                writer.write_event(XmlEvent::Empty(elem))?;
            }
            Position::Lane {
                road_id,
                lane_id,
                s,
                offset,
                orientation,
            } => {
                let mut elem = BytesStart::new("LanePosition");
                elem.push_attribute(("roadId", road_id.as_str()));
                elem.push_attribute(("laneId", lane_id.to_string().as_str()));
                elem.push_attribute(("s", s.to_string().as_str()));
                elem.push_attribute(("offset", offset.to_string().as_str()));
                if let Some(ori) = orientation {
                    elem.push_attribute(("h", ori.h.to_string().as_str()));
                    elem.push_attribute(("pitch", ori.p.to_string().as_str()));
                    elem.push_attribute(("roll", ori.r.to_string().as_str()));
                }
                writer.write_event(XmlEvent::Empty(elem))?;
            }
            Position::Road {
                road_id,
                s,
                t,
                orientation,
            } => {
                let mut elem = BytesStart::new("RoadPosition");
                elem.push_attribute(("roadId", road_id.as_str()));
                elem.push_attribute(("s", s.to_string().as_str()));
                elem.push_attribute(("t", t.to_string().as_str()));
                if let Some(ori) = orientation {
                    elem.push_attribute(("h", ori.h.to_string().as_str()));
                    elem.push_attribute(("pitch", ori.p.to_string().as_str()));
                    elem.push_attribute(("roll", ori.r.to_string().as_str()));
                }
                writer.write_event(XmlEvent::Empty(elem))?;
            }
            Position::RelativeWorld {
                entity,
                dx,
                dy,
                dz,
                orientation,
            } => {
                let mut elem = BytesStart::new("RelativeWorldPosition");
                elem.push_attribute(("entityRef", entity.as_str()));
                elem.push_attribute(("dx", dx.to_string().as_str()));
                elem.push_attribute(("dy", dy.to_string().as_str()));
                elem.push_attribute(("dz", dz.to_string().as_str()));
                writer.write_event(XmlEvent::Start(elem))?;

                let mut ori_elem = BytesStart::new("Orientation");
                ori_elem.push_attribute(("h", orientation.h.to_string().as_str()));
                ori_elem.push_attribute(("p", orientation.p.to_string().as_str()));
                ori_elem.push_attribute(("r", orientation.r.to_string().as_str()));
                ori_elem.push_attribute(("type", "relative"));
                writer.write_event(XmlEvent::Empty(ori_elem))?;

                writer.write_event(XmlEvent::End(BytesEnd::new("RelativeWorldPosition")))?;
            }
            Position::RelativeObject {
                entity,
                dx,
                dy,
                dz,
                orientation,
            } => {
                let mut elem = BytesStart::new("RelativeObjectPosition");
                elem.push_attribute(("entityRef", entity.as_str()));
                elem.push_attribute(("dx", dx.to_string().as_str()));
                elem.push_attribute(("dy", dy.to_string().as_str()));
                elem.push_attribute(("dz", dz.to_string().as_str()));
                writer.write_event(XmlEvent::Start(elem))?;

                let mut ori_elem = BytesStart::new("Orientation");
                ori_elem.push_attribute(("h", orientation.h.to_string().as_str()));
                ori_elem.push_attribute(("p", orientation.p.to_string().as_str()));
                ori_elem.push_attribute(("r", orientation.r.to_string().as_str()));
                ori_elem.push_attribute(("type", "relative"));
                writer.write_event(XmlEvent::Empty(ori_elem))?;

                writer.write_event(XmlEvent::End(BytesEnd::new("RelativeObjectPosition")))?;
            }
            Position::RelativeLane {
                entity,
                ds,
                d_lane,
                offset,
                orientation,
            } => {
                let mut elem = BytesStart::new("RelativeLanePosition");
                elem.push_attribute(("entityRef", entity.as_str()));
                elem.push_attribute(("ds", ds.to_string().as_str()));
                elem.push_attribute(("dLane", d_lane.to_string().as_str()));
                elem.push_attribute(("offset", offset.to_string().as_str()));
                if let Some(ori) = orientation {
                    elem.push_attribute(("h", ori.h.to_string().as_str()));
                    elem.push_attribute(("pitch", ori.p.to_string().as_str()));
                    elem.push_attribute(("roll", ori.r.to_string().as_str()));
                }
                writer.write_event(XmlEvent::Empty(elem))?;
            }
            Position::RelativeRoad {
                entity,
                ds,
                dt,
                orientation,
            } => {
                let mut elem = BytesStart::new("RelativeRoadPosition");
                elem.push_attribute(("entityRef", entity.as_str()));
                elem.push_attribute(("ds", ds.to_string().as_str()));
                elem.push_attribute(("dt", dt.to_string().as_str()));
                if let Some(ori) = orientation {
                    elem.push_attribute(("h", ori.h.to_string().as_str()));
                    elem.push_attribute(("pitch", ori.p.to_string().as_str()));
                    elem.push_attribute(("roll", ori.r.to_string().as_str()));
                }
                writer.write_event(XmlEvent::Empty(elem))?;
            }
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("Position")))?;
        Ok(())
    }

    fn write_story<W: std::io::Write>(&self, writer: &mut Writer<W>, story: &Story) -> Result<()> {
        let mut elem = BytesStart::new("Story");
        elem.push_attribute(("name", story.name.as_str()));
        writer.write_event(XmlEvent::Start(elem))?;

        for act in story.acts.values() {
            self.write_act(writer, act)?;
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("Story")))?;
        Ok(())
    }

    fn write_trigger<W: std::io::Write>(
        &self,
        writer: &mut Writer<W>,
        trigger: &crate::storyboard::Trigger,
    ) -> Result<()> {
        writer.write_event(XmlEvent::Start(BytesStart::new("StartTrigger")))?;
        for group in &trigger.condition_groups {
            self.write_condition_group(writer, group)?;
        }
        writer.write_event(XmlEvent::End(BytesEnd::new("StartTrigger")))?;
        Ok(())
    }

    fn write_condition_group<W: std::io::Write>(
        &self,
        writer: &mut Writer<W>,
        group: &crate::storyboard::ConditionGroup,
    ) -> Result<()> {
        writer.write_event(XmlEvent::Start(BytesStart::new("ConditionGroup")))?;
        for condition in &group.conditions {
            self.write_condition(writer, condition)?;
        }
        writer.write_event(XmlEvent::End(BytesEnd::new("ConditionGroup")))?;
        Ok(())
    }

    fn write_condition<W: std::io::Write>(
        &self,
        writer: &mut Writer<W>,
        condition: &crate::storyboard::Condition,
    ) -> Result<()> {
        let mut cond_elem = BytesStart::new("Condition");
        cond_elem.push_attribute(("name", condition.name.as_str()));
        cond_elem.push_attribute(("delay", condition.delay.to_string().as_str()));

        // Convert ConditionEdge enum to XML string
        let edge_str = match condition.condition_edge {
            crate::storyboard::ConditionEdge::None => "none",
            crate::storyboard::ConditionEdge::Rising => "rising",
            crate::storyboard::ConditionEdge::Falling => "falling",
            crate::storyboard::ConditionEdge::RisingOrFalling => "risingOrFalling",
        };
        cond_elem.push_attribute(("conditionEdge", edge_str));

        writer.write_event(XmlEvent::Start(cond_elem))?;

        // Write condition kind (currently only ByValue supported)
        match &condition.kind {
            crate::storyboard::ConditionKind::ByValue(by_value) => {
                writer.write_event(XmlEvent::Start(BytesStart::new("ByValueCondition")))?;

                match by_value {
                    crate::storyboard::ByValueCondition::SimulationTime { value, rule } => {
                        let mut sim_time = BytesStart::new("SimulationTimeCondition");
                        sim_time.push_attribute(("value", value.to_string().as_str()));

                        let rule_str = match rule {
                            crate::storyboard::ComparisonRule::GreaterOrEqual => "greaterOrEqual",
                            crate::storyboard::ComparisonRule::GreaterThan => "greaterThan",
                            crate::storyboard::ComparisonRule::LessOrEqual => "lessOrEqual",
                            crate::storyboard::ComparisonRule::LessThan => "lessThan",
                            crate::storyboard::ComparisonRule::EqualTo => "equalTo",
                            crate::storyboard::ComparisonRule::NotEqualTo => "notEqualTo",
                        };
                        sim_time.push_attribute(("rule", rule_str));

                        writer.write_event(XmlEvent::Empty(sim_time))?;
                    }
                    crate::storyboard::ByValueCondition::StoryboardElementState {
                        element_type,
                        element_ref,
                        state,
                    } => {
                        let mut elem_state = BytesStart::new("StoryboardElementStateCondition");
                        elem_state.push_attribute(("storyboardElementType", element_type.as_str()));
                        elem_state.push_attribute(("storyboardElementRef", element_ref.as_str()));
                        elem_state.push_attribute(("state", state.as_str()));
                        writer.write_event(XmlEvent::Empty(elem_state))?;
                    }
                    crate::storyboard::ByValueCondition::Parameter(param_cond) => {
                        // Validate parameter exists
                        if !self.parameters.iter().any(|p| p.name == param_cond.parameter_ref) {
                            return Err(ScenarioError::InvalidParameterRef(param_cond.parameter_ref.clone()));
                        }
                        
                        let mut param_cond_elem = BytesStart::new("ParameterCondition");
                        param_cond_elem.push_attribute(("parameterRef", param_cond.parameter_ref.as_str()));
                        param_cond_elem.push_attribute(("value", param_cond.value.as_str()));

                        let rule_str = match param_cond.rule {
                            crate::storyboard::ComparisonRule::GreaterOrEqual => "greaterOrEqual",
                            crate::storyboard::ComparisonRule::GreaterThan => "greaterThan",
                            crate::storyboard::ComparisonRule::LessOrEqual => "lessOrEqual",
                            crate::storyboard::ComparisonRule::LessThan => "lessThan",
                            crate::storyboard::ComparisonRule::EqualTo => "equalTo",
                            crate::storyboard::ComparisonRule::NotEqualTo => "notEqualTo",
                        };
                        param_cond_elem.push_attribute(("rule", rule_str));

                        writer.write_event(XmlEvent::Empty(param_cond_elem))?;
                    }
                }

                writer.write_event(XmlEvent::End(BytesEnd::new("ByValueCondition")))?;
            }
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("Condition")))?;
        Ok(())
    }

    fn write_act<W: std::io::Write>(&self, writer: &mut Writer<W>, act: &Act) -> Result<()> {
        let mut elem = BytesStart::new("Act");
        elem.push_attribute(("name", act.name.as_str()));
        writer.write_event(XmlEvent::Start(elem))?;

        for mg in act.maneuver_groups.values() {
            self.write_maneuver_group(writer, mg)?;
        }

        // StartTrigger
        if let Some(trigger) = &act.start_trigger {
            // Use custom trigger if set
            self.write_trigger(writer, trigger)?;
        } else {
            // Default: start immediately at t=0
            writer.write_event(XmlEvent::Start(BytesStart::new("StartTrigger")))?;
            writer.write_event(XmlEvent::Start(BytesStart::new("ConditionGroup")))?;
            let mut cond = BytesStart::new("Condition");
            cond.push_attribute(("name", "ActStartCondition"));
            cond.push_attribute(("delay", "0"));
            cond.push_attribute(("conditionEdge", "none"));
            writer.write_event(XmlEvent::Start(cond))?;
            writer.write_event(XmlEvent::Start(BytesStart::new("ByValueCondition")))?;
            let mut sim_time = BytesStart::new("SimulationTimeCondition");
            sim_time.push_attribute(("value", "0"));
            sim_time.push_attribute(("rule", "greaterOrEqual"));
            writer.write_event(XmlEvent::Empty(sim_time))?;
            writer.write_event(XmlEvent::End(BytesEnd::new("ByValueCondition")))?;
            writer.write_event(XmlEvent::End(BytesEnd::new("Condition")))?;
            writer.write_event(XmlEvent::End(BytesEnd::new("ConditionGroup")))?;
            writer.write_event(XmlEvent::End(BytesEnd::new("StartTrigger")))?;
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("Act")))?;
        Ok(())
    }

    fn write_maneuver_group<W: std::io::Write>(
        &self,
        writer: &mut Writer<W>,
        mg: &ManeuverGroup,
    ) -> Result<()> {
        let mut elem = BytesStart::new("ManeuverGroup");
        elem.push_attribute(("maximumExecutionCount", "1"));
        elem.push_attribute(("name", mg.name.as_str()));
        writer.write_event(XmlEvent::Start(elem))?;

        // Actors
        writer.write_event(XmlEvent::Start(BytesStart::new("Actors")))?;
        for actor in &mg.actors {
            let mut ref_elem = BytesStart::new("EntityRef");
            ref_elem.push_attribute(("entityRef", actor.as_str()));
            writer.write_event(XmlEvent::Empty(ref_elem))?;
        }
        writer.write_event(XmlEvent::End(BytesEnd::new("Actors")))?;

        // Get first actor for action context (or empty string if no actors)
        let actor = mg.actors.first().map(|s| s.as_str()).unwrap_or("");

        // Maneuvers
        for maneuver in &mg.maneuvers {
            self.write_maneuver(writer, maneuver, actor)?;
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("ManeuverGroup")))?;
        Ok(())
    }

    fn write_maneuver<W: std::io::Write>(
        &self,
        writer: &mut Writer<W>,
        maneuver: &Maneuver,
        actor: &str,
    ) -> Result<()> {
        let mut elem = BytesStart::new("Maneuver");
        elem.push_attribute(("name", maneuver.name.as_str()));
        writer.write_event(XmlEvent::Start(elem))?;

        for event in &maneuver.events {
            self.write_event(writer, event, actor)?;
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("Maneuver")))?;
        Ok(())
    }

    fn write_event<W: std::io::Write>(
        &self,
        writer: &mut Writer<W>,
        event: &Event,
        actor: &str,
    ) -> Result<()> {
        let mut elem = BytesStart::new("Event");
        elem.push_attribute(("name", event.name.as_str()));
        elem.push_attribute(("priority", "overwrite"));
        writer.write_event(XmlEvent::Start(elem))?;

        // Actions
        for action in &event.actions {
            self.write_action(writer, action, actor)?;
        }

        // StartTrigger
        if let Some(trigger) = &event.start_trigger {
            // Use custom trigger if set
            self.write_trigger(writer, trigger)?;
        } else {
            // Default: start when act begins (t=0)
            writer.write_event(XmlEvent::Start(BytesStart::new("StartTrigger")))?;
            writer.write_event(XmlEvent::Start(BytesStart::new("ConditionGroup")))?;
            let mut cond = BytesStart::new("Condition");
            cond.push_attribute(("name", "EventStartCondition"));
            cond.push_attribute(("delay", "0"));
            cond.push_attribute(("conditionEdge", "none"));
            writer.write_event(XmlEvent::Start(cond))?;
            writer.write_event(XmlEvent::Start(BytesStart::new("ByValueCondition")))?;
            let mut sim_time = BytesStart::new("SimulationTimeCondition");
            sim_time.push_attribute(("value", "0"));
            sim_time.push_attribute(("rule", "greaterOrEqual"));
            writer.write_event(XmlEvent::Empty(sim_time))?;
            writer.write_event(XmlEvent::End(BytesEnd::new("ByValueCondition")))?;
            writer.write_event(XmlEvent::End(BytesEnd::new("Condition")))?;
            writer.write_event(XmlEvent::End(BytesEnd::new("ConditionGroup")))?;
            writer.write_event(XmlEvent::End(BytesEnd::new("StartTrigger")))?;
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("Event")))?;
        Ok(())
    }

    fn write_action<W: std::io::Write>(
        &self,
        writer: &mut Writer<W>,
        action: &Action,
        actor: &str,
    ) -> Result<()> {
        let mut elem = BytesStart::new("Action");
        elem.push_attribute(("name", "action"));
        writer.write_event(XmlEvent::Start(elem))?;

        writer.write_event(XmlEvent::Start(BytesStart::new("PrivateAction")))?;

        match action {
            Action::Speed(speed) => {
                writer.write_event(XmlEvent::Start(BytesStart::new("LongitudinalAction")))?;
                writer.write_event(XmlEvent::Start(BytesStart::new("SpeedAction")))?;

                let mut dyn_elem = BytesStart::new("SpeedActionDynamics");
                dyn_elem.push_attribute((
                    "dynamicsShape",
                    format!("{:?}", speed.shape).to_lowercase().as_str(),
                ));
                dyn_elem.push_attribute(("value", speed.transition_duration.to_string().as_str()));
                dyn_elem.push_attribute(("dynamicsDimension", "time"));
                writer.write_event(XmlEvent::Empty(dyn_elem))?;

                writer.write_event(XmlEvent::Start(BytesStart::new("SpeedActionTarget")))?;
                let mut target_elem = BytesStart::new("AbsoluteTargetSpeed");
                target_elem.push_attribute(("value", speed.target_speed.to_string().as_str()));
                writer.write_event(XmlEvent::Empty(target_elem))?;
                writer.write_event(XmlEvent::End(BytesEnd::new("SpeedActionTarget")))?;

                writer.write_event(XmlEvent::End(BytesEnd::new("SpeedAction")))?;
                writer.write_event(XmlEvent::End(BytesEnd::new("LongitudinalAction")))?;
            }
            Action::LaneChange(lane_change) => {
                writer.write_event(XmlEvent::Start(BytesStart::new("LateralAction")))?;
                writer.write_event(XmlEvent::Start(BytesStart::new("LaneChangeAction")))?;

                writer.write_event(XmlEvent::Start(BytesStart::new("LaneChangeActionDynamics")))?;
                let mut dyn_elem = BytesStart::new("Dynamics");
                dyn_elem.push_attribute((
                    "dynamicsShape",
                    format!("{:?}", lane_change.shape).to_lowercase().as_str(),
                ));
                dyn_elem.push_attribute((
                    "value",
                    lane_change.transition_duration.to_string().as_str(),
                ));
                dyn_elem.push_attribute(("dynamicsDimension", "time"));
                writer.write_event(XmlEvent::Empty(dyn_elem))?;
                writer.write_event(XmlEvent::End(BytesEnd::new("LaneChangeActionDynamics")))?;

                writer.write_event(XmlEvent::Start(BytesStart::new("LaneChangeTarget")))?;
                let mut target_elem = BytesStart::new("RelativeTargetLane");
                target_elem.push_attribute(("entityRef", actor));
                target_elem
                    .push_attribute(("value", lane_change.target_lane_offset.to_string().as_str()));
                writer.write_event(XmlEvent::Empty(target_elem))?;
                writer.write_event(XmlEvent::End(BytesEnd::new("LaneChangeTarget")))?;

                writer.write_event(XmlEvent::End(BytesEnd::new("LaneChangeAction")))?;
                writer.write_event(XmlEvent::End(BytesEnd::new("LateralAction")))?;
            }
            Action::Position(position_action) => {
                writer.write_event(XmlEvent::Start(BytesStart::new("TeleportAction")))?;
                self.write_position(writer, &position_action.position)?;
                writer.write_event(XmlEvent::End(BytesEnd::new("TeleportAction")))?;
            }
            Action::Distance(distance_action) => {
                writer.write_event(XmlEvent::Start(BytesStart::new("LongitudinalAction")))?;
                writer.write_event(XmlEvent::Start(BytesStart::new(
                    "LongitudinalDistanceAction",
                )))?;

                let mut entity_elem = BytesStart::new("EntityRef");
                entity_elem.push_attribute(("entityRef", distance_action.entity_ref.as_str()));
                writer.write_event(XmlEvent::Empty(entity_elem))?;

                let mut dist_elem = BytesStart::new("Distance");
                dist_elem.push_attribute(("value", distance_action.distance.to_string().as_str()));
                dist_elem
                    .push_attribute(("freespace", distance_action.freespace.to_string().as_str()));
                writer.write_event(XmlEvent::Empty(dist_elem))?;

                writer.write_event(XmlEvent::End(BytesEnd::new("LongitudinalDistanceAction")))?;
                writer.write_event(XmlEvent::End(BytesEnd::new("LongitudinalAction")))?;
            }
        }

        writer.write_event(XmlEvent::End(BytesEnd::new("PrivateAction")))?;
        writer.write_event(XmlEvent::End(BytesEnd::new("Action")))?;
        Ok(())
    }

    fn write_stop_trigger<W: std::io::Write>(&self, writer: &mut Writer<W>) -> Result<()> {
        if let Some(stop_trigger) = &self.storyboard.stop_trigger {
            writer.write_event(XmlEvent::Start(BytesStart::new("StopTrigger")))?;
            writer.write_event(XmlEvent::Start(BytesStart::new("ConditionGroup")))?;

            match &stop_trigger.condition {
                crate::storyboard::StopCondition::SimulationTime { seconds } => {
                    let mut cond_elem = BytesStart::new("Condition");
                    cond_elem.push_attribute(("name", "StopCondition"));
                    cond_elem.push_attribute(("delay", "0"));
                    cond_elem.push_attribute(("conditionEdge", "rising"));
                    writer.write_event(XmlEvent::Start(cond_elem))?;

                    writer.write_event(XmlEvent::Start(BytesStart::new("ByValueCondition")))?;
                    let mut time_elem = BytesStart::new("SimulationTimeCondition");
                    time_elem.push_attribute(("value", seconds.to_string().as_str()));
                    time_elem.push_attribute(("rule", "greaterThan"));
                    writer.write_event(XmlEvent::Empty(time_elem))?;
                    writer.write_event(XmlEvent::End(BytesEnd::new("ByValueCondition")))?;

                    writer.write_event(XmlEvent::End(BytesEnd::new("Condition")))?;
                }
                crate::storyboard::StopCondition::StoryboardElementState {
                    element_type,
                    element_ref,
                    state,
                    delay,
                } => {
                    let mut cond_elem = BytesStart::new("Condition");
                    cond_elem.push_attribute(("name", "StopCondition"));
                    cond_elem.push_attribute(("delay", delay.to_string().as_str()));
                    cond_elem.push_attribute(("conditionEdge", "rising"));
                    writer.write_event(XmlEvent::Start(cond_elem))?;

                    writer.write_event(XmlEvent::Start(BytesStart::new("ByValueCondition")))?;
                    let mut elem_state = BytesStart::new("StoryboardElementStateCondition");
                    elem_state.push_attribute(("storyboardElementType", element_type.as_str()));
                    elem_state.push_attribute(("storyboardElementRef", element_ref.as_str()));
                    elem_state.push_attribute(("state", state.as_str()));
                    writer.write_event(XmlEvent::Empty(elem_state))?;
                    writer.write_event(XmlEvent::End(BytesEnd::new("ByValueCondition")))?;

                    writer.write_event(XmlEvent::End(BytesEnd::new("Condition")))?;
                }
            }

            writer.write_event(XmlEvent::End(BytesEnd::new("ConditionGroup")))?;
            writer.write_event(XmlEvent::End(BytesEnd::new("StopTrigger")))?;
        } else {
            // No stop trigger defined, write empty element
            writer.write_event(XmlEvent::Empty(BytesStart::new("StopTrigger")))?;
        }
        Ok(())
    }
}
